---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Set a hostname
    ansible.builtin.hostname:
      name: workstation

  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install updates
    ansible.builtin.apt: 
      name: "*"
      state: latest

  - name: Install packages
    ansible.builtin.apt:
      pkg:
        - chromium-browser
        - doublecmd-common
        - openvpn
        - network-manager-openvpn
        - network-manager-openvpn-gnome
        - neofetch
        - cmatrix
        - audacious
        - pwgen
        - cherrytree
        - atop
        - htop
        - btop
        - iftop
        - traceroute
        - netdiscover
        - tor
        - mpv
        - vim
        - psmisc
        - tree
        - virtualbox
        - virtualbox-guest-additions-iso
        - putty
        - iperf3
        - powertop
        - openssh-server
        - nmap
        - smartmontools
        - shellcheck
        - sysstat
        - git
        - ncdu
        - samba
        - docker.io

  - name: Remove irrelevant packages
    ansible.builtin.apt:
      autoremove: yes
