---
- hosts: all
  become: true

  tasks:
  - name: update apt cache
    ansible.builtin.apt:
      update_cache: yes

  - name: install updates
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: remove irrelevant packages
    ansible.builtin.apt:
      autoremove: yes
