---

- hosts: all
  become: true

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes

    - name: install updates
      apt: 
        name: "*"
        state: latest

    - name: remove irrelevant packages
      apt:
        autoremove: yes
